package com.patan.tmdbapp.util

class Constants {
    companion object {
        const val API_KEY="Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjlmYTE2N2ZmMTIwYzY2NzI2YThhMzE5YmZmNzFmMSIsIm5iZiI6MTcyMTgxMTI4Ny4yMjk3MzUsInN1YiI6IjY2OWU1N2M1ZGY5NGY4MDBjNDQ3YTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.QtkRlBrSrUUFCJPgkoIytPaurEhfi3NY0XPhFn9pnI4"
        const val SEARCH_URL="https://api.themoviedb.org/3/search/"
        const val BASE_URL="https://api.themoviedb.org/"
        const val IMAGE_URL="https://image.tmdb.org/t/p/w500"
        const val BEARER_UP=        "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjlmYTE2N2ZmMTIwYzY2NzI2YThhMzE5YmZmNzFmMSIsIm5iZiI6MTcyMTg0MDA1Mi42NjM5MDYsInN1YiI6IjY2OWU1N2M1ZGY5NGY4MDBjNDQ3YTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.KL6IJzZyWnyIzwls6jnNTYRcTGIKhkL6bPAvLeOmSOM"
        const val BEARER_TOP=       "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjlmYTE2N2ZmMTIwYzY2NzI2YThhMzE5YmZmNzFmMSIsIm5iZiI6MTcyMTg0MDA1Mi42NjM5MDYsInN1YiI6IjY2OWU1N2M1ZGY5NGY4MDBjNDQ3YTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.KL6IJzZyWnyIzwls6jnNTYRcTGIKhkL6bPAvLeOmSOM"
        const val BEARER_NOW=       "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjlmYTE2N2ZmMTIwYzY2NzI2YThhMzE5YmZmNzFmMSIsIm5iZiI6MTcyMTg0MDA1Mi42NjM5MDYsInN1YiI6IjY2OWU1N2M1ZGY5NGY4MDBjNDQ3YTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.KL6IJzZyWnyIzwls6jnNTYRcTGIKhkL6bPAvLeOmSOM"
        const val BEARER_POPULAR=   "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjlmYTE2N2ZmMTIwYzY2NzI2YThhMzE5YmZmNzFmMSIsIm5iZiI6MTcyMTgxMTI4Ny4yMjk3MzUsInN1YiI6IjY2OWU1N2M1ZGY5NGY4MDBjNDQ3YTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.QtkRlBrSrUUFCJPgkoIytPaurEhfi3NY0XPhFn9pnI4"
        const val BEARER_DETAILS=   "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZjlmYTE2N2ZmMTIwYzY2NzI2YThhMzE5YmZmNzFmMSIsIm5iZiI6MTcyMTgxMTI4Ny4yMjk3MzUsInN1YiI6IjY2OWU1N2M1ZGY5NGY4MDBjNDQ3YTZlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.QtkRlBrSrUUFCJPgkoIytPaurEhfi3NY0XPhFn9pnI4"
    }
}